### PR TITLE
Test/setup

### PR DESCRIPTION
**Pull request by rvvergara**
Hi @rgavinc,

Kindly check these initial commits. Essentially for now I installed:

- `enzyme`
- `enzyme-adapter-react-16`
- `enzyme-to-json`

I also just created files that will set up the project for testing with enzyme

`jest.config.json`
`src/setupTests.js`

Also wrote tests for each component currently present.

### CODE REVIEW

**Comment by rvvergara** [comment]
Hi @rgavinc. Kindly see [this](https://github.com/zero-to-mastery/drum-root/blob/9229f0539c5e54c689bea5de1e7f3654b81a570f/src/test/Components/FormWrapper.test.js#L15) test. I cannot seem to make it pass. I am trying to assert that the `onSubmit` prop is being called whenever the form is submitted.

**Comment by rvvergara** [comment]
> This is looking awesome, really good work rvvergara! I just have two requests:
> 
>     * instead of creating a new folder called `test` could you move each component's test into it's folder within `components`? For example `test/Components/Drumpad.test.js` would become `Components/DrumPad/index.test.js`. This way we can keep the tests and react code organized better :)
> 
>     * Instead of using snapshots as our default tests could you change them to the default test that I included in the Trello task? From my experience with snapshot tests, they cause more trouble then help in a shared repository. The snapshots end up getting a ton of merge conflicts and they don't provide much benefit in the long run.

Got it @rgavinc! :) Will do that. Thanks. To also reiterate what I said in Discord, I'll just remove also the test case for the `onSubmit` calling.

**Comment by rvvergara** [comment]
@rgavinc, requested changes implemented! :) Kindly review. Thanks

**Comment by Dhaval1403** [comment]
Hey, I have reviewed your changes and it looks good to me :)

**Comment by rvvergara** [comment]
Thanks @Dhaval1403. You're awesome man! Glad to contribute

**Pull request merged**
