### PR TITLE
changed style of signin page

### PR DESCRIPTION
**Pull request by MikePassetti**
Changed the style of the signin page and updated some of the packages
@joshtru

### CODE REVIEW

**Comment by MikePassetti** [comment]
Sure I can do that. Not entirely sure how though. Do I manually change the dependencies back to how they were? Or is there another way?

**Comment by zbc** [comment]
The key here is to maintain both `package.json` and `package-lock.json` files unchanged. Try to run `npm uninstall tachyons` to remove `tachyons` in `package.json`, then change next version back to `"^9.1.1"` in `package.json`, and run `npm install` again. 
If above method won't work, the final solution I can think of is to copy original `package.json` and `package-lock.json` files and replace your local. Then remove `node_modules` and run `npm install`.

**Comment by MikePassetti** [comment]
Thanks for the response! I'll give that a try.

**Comment by zbc** [comment]
It seems like the `package-lock.json` file still been modified. And there are `yarn.berry.js`  and `yarnrc.yml` files being added too. Maybe try to remove `node_modules`, `.yarn/releases/yarn-berry.js` and `yarnrc.yml` files and download the original `package.json` and `package-lock.json` to reinstall.

**Comment by zbc** [comment]
Good job on removing unnecessary dependencies. It looks great 👍 .
The final part is I notice there are some linting errors that need to be fixed. 
You can run `npm run lint:fix`. It will help to fix some errors.
The rest you have to fix it individually. You can run `npm run lint` to check if it passes all. 
Thanks!

**Comment by MikePassetti** [comment]
Thank you for guiding me through the process! As this was my first pr I really appreciate all the help.

**Comment by zbc** [comment]
You're welcome. I'm glad to help you out. You did a great job. I cannot tell this is your first PR. Keep working!

**Pull request merged**
